// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mudaotdzjtkkfoyrppyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11ZGFvdGR6anRra2ZveXJwcHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODY0NzUsImV4cCI6MjA1ODY2MjQ3NX0.BrIO2nDZXah7GeIFwmz36CyW9nFw0R7lou-jhqd4FHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);